apiVersion: batch/v1
kind: Job
metadata:
  name: rpi1-build
spec:
  template:
    metadata:
      name: rpi1-build
      labels:
        description: crosscompiler
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: description
                    operator: In
                    values:
                      - crosscompiler
      containers:
      - name: rpi1-build
        image: andyg42/ubuntu-crosstool:9
        env:
          - name: SAMPLE_TO_BUILD
            value: testconfigs/armv6-rpi-gnueabihf-glibc2.24
          - name: S3_OUTPUT_URI
            value: s3://{{output bucket}}
        volumeMounts:
        - mountPath: /home/build/.aws
          name: aws-credentials-secret
        - mountPath: /home/build/testconfigs
          name: test-configs
      volumes:
      - name: aws-credentials-secret
        secret:
          secretName: aws-credentials-secret
      - name: test-configs
        configMap:
          name: test-build-configs
      restartPolicy: OnFailure
  backoffLimit: 4
